### ISSUE TITLE
Issues closed too soon

### ISSUE THREAD

**Issue by j-f1** [probot/no-response#12]
This was just installed on desktop/desktop, and it has closed a whole bunch of issues with the `more-information-needed` label, most of which have been active fairly recently, and a few of which were opened today:

https://github.com/desktop/desktop/issues/3302#event-1341126132
https://github.com/desktop/desktop/issues/3320#event-1341126180
https://github.com/desktop/desktop/issues/3263#event-1341126214
https://github.com/desktop/desktop/issues/3283#event-1341126246
https://github.com/desktop/desktop/issues/3300#event-1341126273
https://github.com/desktop/desktop/issues/3294#event-1341126320
https://github.com/desktop/desktop/issues/3237#event-1341126355
https://github.com/desktop/desktop/issues/3279#event-1341126404
https://github.com/desktop/desktop/issues/3219#event-1341126440
https://github.com/desktop/desktop/issues/3208#event-1341126473
https://github.com/desktop/desktop/issues/3125#event-1341126514
https://github.com/desktop/desktop/issues/3182#event-1341126564
https://github.com/desktop/desktop/issues/3168#event-1341126604
https://github.com/desktop/desktop/issues/3111#event-1341126630
https://github.com/desktop/desktop/issues/2623#event-1341126697
https://github.com/desktop/desktop/issues/3223#event-1341126727
https://github.com/desktop/desktop/issues/2812#event-1341126093

[Our `.github/no-response.yml`](https://github.com/desktop/desktop/blob/master/.github/no-response.yml):

```yml
# Configuration for no-response - https://github.com/probot/no-response

# Number of days of inactivity before an Issue is closed for lack of response
daysUntilClose: 14
# Label requiring a response
# TODO: also close `needs-reproduction` issues (blocked by https://github.com/probot/no-response/issues/11)
responseRequiredLabel: more-information-needed
# Comment to post when closing an issue due to lack of response. 
closeComment: >
  Thank you for your issue!
  
  We haven’t gotten a response to our questions above.
  With only the information that is currently in the issue,
  we don’t have enough information to take action.
  We’re going to close this but don’t hesitate to reach out
  if you have or find the answers we need.
  If you answer our questions above, a maintainer will reopen this issue.
```

Do you know why it would do this?
